### ISSUE TITLE
Can not use JsonRecyclerView in Fragment

### ISSUE THREAD

**Issue by hoangkhoatv** [smuyyh/JsonViewer#1]
![untitled](https://user-images.githubusercontent.com/19345656/34138343-940178fa-e4a1-11e7-9dbb-eaabf7c3f2f1.png)

**Comment by smuyyh** [comment]
((JsonRecyclerView) (view.findViewById(....)))

**Comment by hoangkhoatv** [comment]
>

> ``

**Comment by hoangkhoatv** [comment]
Thanks! I added two line
 compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.android.support:recyclerview-v7:26.1.0'
