### ISSUE TITLE
How get text size?

### ISSUE THREAD

**Issue by alexei-28** [smuyyh/JsonViewer#10]
to set text size I use this:

```
JsonRecyclerView jsonRecyclerView = findViewById(R.id.jsonRecyclerView);
jsonRecyclerView.setTextSize(15f);
```

Nice.
Now I need visa versa. How get programmatically text size of `jsonRecyclerView`?

**Comment by smuyyh** [comment]
see ```com.yuyh.jsonviewer.library.adapter. BaseJsonViewerAdapter```
