### ISSUE TITLE
JsonViewer not displaying a JSON object with name (key) spanning over 1 line

### ISSUE THREAD

**Issue by minadaki** [smuyyh/JsonViewer#6]
Hello,

It seems that the library does not work correctly when there is a JSON object with name (key) spanning over 1 line.

In order to demonstrate the problem I ran 2 tests and grabbed screenshots. Both tests were on the same phone (Samsung S8, Android Oreo) and had the exact same JSON data as input. The only difference is that one test had font size 12 (mRecyclewView.setTextSize(12)) and the other test had font size 15 (mRecyclewView.setTextSize(15)).

Please notice the difference associated-device-detailed-statistics JSON object. With the larger font no data can be seen for this object.

![small font no error2](https://user-images.githubusercontent.com/31401053/42631106-db87d200-85e1-11e8-9c64-038994529d03.png)
![big font error](https://user-images.githubusercontent.com/31401053/42631107-dba46ab4-85e1-11e8-9339-b80cea1b4e69.png)
![small font no error1](https://user-images.githubusercontent.com/31401053/42631108-dbc10e4e-85e1-11e8-90cf-5ebf83683d54.png)

**Comment by smuyyh** [comment]
@minadaki you can wrap a HorizontalScrollView out of JsonRecyclerView

```java
<HorizontalScrollView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fillViewport="true"
    android:orientation="vertical">

	<com.yuyh.jsonviewer.library.JsonRecyclerView
	    android:id="@+id/rv_json"
	    android:layout_width="match_parent"
	    android:layout_height="wrap_content" />
</HorizontalScrollView>
```

**Comment by minadaki** [comment]
Thank you. The workaround works.
